[shaders]
lambert = { vert = "lambert.vert", frag = "lambert.frag" }
depth = { vert = "depth.vert", frag = "depth.frag" }

[textures]

[fonts]
main = { path = "capital-hill.ttf", size = 12 }

[models]
fish = "Fish.glb"

[texts]
gamepad_mappings = "general/mappings.txt"
